version: '3.4'
services:
  # bionic gpu:
  workspace-bionic-gpu-vnc:
    build:
      context: docker
      dockerfile: bionic-gpu.Dockerfile
      network: host
    image: deep-learning-workspace:bionic-gpu-vnc
    container_name: deep-learning-workspace-gpu
    privileged: true
    environment:
        # set VNC login password here:
        - VNC_PASSWORD=deeplearning
    volumes:
      # mount your source code workspace here:
      - $PWD/workspace:/workspace
      # mount your dataset here:
    ports:
      # HTML5 VNC:
      - 40080:80
      # standard VNC client:
      - 45901:5901
      # supervisord admin:
      - 49001:9001
      # jupyter notebook:
      - 48888:8888
      - 48889:8889
