version: '3.4'
services:
  # cpu development:
  workspace-bionic-cpu-vnc:
    build:
      context: docker
      dockerfile: cpu.Dockerfile
      network: host
    image: x-vectornet-workspace:bionic-cpu-vnc
    container_name: x-vectornet-workspace-cpu
    privileged: true
    environment:
        # set VNC login password here:
        - VNC_PASSWORD=sfbp
    volumes:
      # mount your source code workspace here:
      - $PWD/workspace:/workspace
      # mount your dataset here:
    ports:
      # HTML5 VNC:
      - 40080:80
      # standard VNC client:
      - 45901:5901
      # supervisord admin:
      - 49001:9001
  # gpu development:
  workspace-bionic-gpu-vnc:
    build:
      context: docker
      dockerfile: gpu.Dockerfile
      network: host
    image: x-vectornet-workspace:bionic-gpu-vnc
    container_name: x-vectornet-workspace-gpu
    privileged: true
    environment:
        # set VNC login password here:
        - VNC_PASSWORD=sfbp
    volumes:
      # mount your source code workspace here:
      - $PWD/workspace:/workspace
      # mount your dataset here:
    ports:
      # HTML5 VNC:
      - 40080:80
      # standard VNC client:
      - 45901:5901
      # supervisord admin:
      - 49001:9001